name: enum_extension
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.1 <3.0.0'


dependencies:
  analyzer: ^2.3.0
  build: ^2.1.0
  build_config: ^1.0.0
  source_gen: ^1.1.0
  enum_extension_annotation:
    path: ../enum_extension_annotation

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
